# -*- coding: utf-8 -*-
"""PythonAssignmentP1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8aVThoBSHCRPmdfsFC4T86LE8BRVCf-
"""
# exercise 1
a = 50
b = 10
if a>b:
  print("Hello World")

# exercise 2
a = 50
b = 10
if a != b:
  print("Hello World")

#exercise 3
a = 50
b = 10
if a == b:
  print('Yes')
else:
  print('No')

#exercise 4
a = 50
b = 10
if a == b:
  print('1')
elif a > b :
    print('2')
else:
    print('3')

# exercise 5
a = 10
b = 10
c = 20
d = 20
if a == b and c == d:
  print('Hello')

if a == b or c == d:
  print('Hello')

# exercise 6
if 5>2:
  print('Yes')
  a = 2
  b = 5
  print('Yes') if a == b else print('No')

# exercise 7
a = 2
b = 50
c = 2
if a or b == c:
  print('Yes')

# exercise 8
num = int(input('enter number:'))
if num % 2 == 0 :
  print(num,'EVEN')
else:
  print(num,'ODD')

# exercise 9
Nationality =input('Nationality:')
if Nationality == "MM":
  print('Eligible to vote')
else:
  print('Not eligible to vote')

# exercise 10
base = 30
height = 100
area = base * height / 2
print("Area of a triangle :", area )

# exercise 11
list = [10,20,30]
print('Largest number:',list[2])

# exercise 12
x = int(input("Enter number of tickets:"))
if (x < 10 ):
  price = (x*20)
  print("You have to pay", price)
elif(x>=10 and x<20):
    price = ((x*20)-(x*20)*0.1)
    print("You have to pay", price)
elif(x==20):
    price=((x*20)-(x*20)*0.2)
    print("You have to pay",price)
else:
  print("You cannot buy more than 20 tickets")

# exercise 13
x = float(input("Enter your test:"))
if (x>=80 and x<=100):
  print("Your GPA is A")
if (x>=70 and x<=79):
  print("Your GPA is B")
if (x>=60 and x<=69):
  print("Your GPA is C")
if (x>=50 and x<=59):
  print("Your GPA is D")
if (x>=0 and x<=49):
  print("Your GPA is E")

# exercise 14
x = int(input("Number of passengers:"))
y = (x/10)
if y != 0:
   z = int(y+1)
   print("Numbers of trips",z)
else:
   print("Numbers of trips",y)

# exercise 15
x = float(input("Enter your test:"))
if (x>=90):
  print("Your Grade is A")
if (x>=85 and x<=89):
  print("Your Grade  is A-")
if (x>=80 and x<=84):
  print("Your Grade  is B+")
if (x>=75 and x<=79):
  print("Your Grade  is B")
if (x>=70 and x<=74):
  print("Your Grade  is B-")
if (x>=65 and x<=69):
  print("Your Grade  is C+")
if (x>=60 and x<=64):
  print("Your Grade  is C")
if (x>=55 and x<=59):
  print("Your Grade is C-")
if (x>=50 and x<=54):
  print("Your Grade  is D")
if (x>=0 and x<=49):
  print("Your Grade  is F")

